---
title: 流程控制与错误处理
date: 2016-05-17 18:36:49
tags:
- javascript
- 流程控制和错误处理
categories: 笔记
---
> Energy and persistence conquer all things.

在JavaScript中，任何表达式(expression)都可以看作一条语句(statement)，每条语句可以使用分号( ; )来分隔。你可以在每行书写一条语句；也可以在一行书写多条语句。但是我们推荐在书写代码的时候采用第一种方式，以便于后期的代码维护。

## 语句块(Block Statement)
大多数程序都使用语句块来给语句分组，这样可以使语句的结构清晰明了。我们使用一对花括号（ {} ）来分组语句块，如下所示：

```javascript
    {
       statement_1;   statement_2;
       statement_3;
       ...
       statement_n;
    }
```

示例
语句块通常大多数用于流程控制，如 if, for, while等等。

```javascript
    while (x < 10){
      x++;
    }
```
这里{ x++; } 就是语句块。

## 条件判断语句(Conditional Statements)
条件判断语句指的是根据指定的条件所返回的结果（真或假或其它预定义的），来执行特定的语句。JavaScript提供了两种条件判断语句：if...else 和 switch。

### if...else语句
当一个逻辑条件为真，用if语句执行一个语句。当这个条件为假，使用可选择的else从句来执行这个语句。

在条件表达式中最好不要使用“=”来判断条件是否相等，因为这会产生非预期结果。不要使用下面的代码：
```javascript
   if (x = y) {
     /* do the right thing */
   } 
```

如果你需要在条件表达式中使用赋值，一个共同的习惯是在赋值语句前后额外的添加一对括号。例如：
```javascript
   if ((x = y)) {
     /* do the right thing */
   }
```

下面这些值将被计算出 false:
 - false
 - undefined
 - null
 - 0
 - NaN
 - 空字符串("")
当传递给条件语句时，所有其他值，包括所有对象会被计算为 true。

**请不要混淆原始的布尔值true和false与布尔对象的值true和false。**例如：
```javascript
   var b = new Boolean(false);
   if(b) //this condition evaluates to true
   if(b == true) //this condition evaluates to false
```

例如
在下面的例子中，如果一个文本对象中的字符串长度是3，函数checkData返回true；否则，函数显示一个alert的弹出框消息并返回false。
```javascript
   function checkData() {
     if (document.form1.threeChar.value.length == 3) {
       return true;
     } else {
       alert("Enter exactly three characters. " +
         document.form1.threeChar.value + " is not valid.");
       return false;
     }
   } 
```

### switch语句(Switch Statement)
开关语句允许一个程序求一个表达式的值并且尝试去匹配表达式的值到一个case label。如果匹配成功，这个程序执行相关的语句。开关语句如下所示：
```javascript
  switch (expression) {
     case label_1:
        statements_1
        [break;]
     case label_2:
        statements_2
        [break;]
     ...
     default:
        statements_def
        [break;]
  }  
```

## 循环语句(Loop Statement)
循环语句是一系列反复执行直到符合特定条件的命令。JavaScript 支持 for, do while, while这些循环语句，还有Label (label 本身不是一个循环语句，但是经常和这些语句一起使用)。另外，你可以在循环语句中使用break和continue 语句。另一个语句：for...in也反复执行语句，但它是用来操作对象的。

### 标签语句(label Statement)
标签语句提供一种使你同一程序的另一处找到它的标识。例如，你可以用一个标签来识别一个循环，并用break或continue语句来说明一个程序是否要中断这个循环或是继续执行。如下所示：
```javascript
    label:
        statement
```
label的值可以是js的任何非保留字符标识符。用label标识的语句可以是任何语句。

例如：
```javascript
    markLoop:
    while(theMark == true){
        doSomething();
    }
```

## 中断语句(break Statement)
使用中断语句终止循环、开关或与标签语句连接。

 - 当你使用没有带标签语句的中断语句（break）时，while,do-while,for或switch封闭的内部语句将立即终止，并转移到后面的语句执行。
 - 当你使用带有标签语句的中断语句(break)时，将终止在特定的标签语句。
 
 中断语句的语法如下：
 1.break;
 2.break label;
 
 第一种语法形式用于终止在循环体或者switch的封闭内部；第二种语法形式用于在特定的封闭标签语句。
 
 示例1：
 下面的例子中，对一个数组里的元素进行循环处理，直到数组元素下标等于theValue的值：
 ```javascript
    for(var i=0;i<a.length;i++){
        if(a[i] == theValue){
            break;
        }
    }
 ```

示例2：中断跳到标签语句
```javascript
    var x = 0;
    var z = 0;
    labelCancelLoops: while(true){
        console.log("Outer loops:" + x);
        x += 1;
        z = 1;
        while(true){
            console.log("Inner loops: "+z);
            z+=1;
            if(z === 10 && x === 10){
                break labelCancelLoops;
            }else if(z === 10){
                break;
            }
        }
    }
```

## 连续语句(continue Statement)
连续语句用于重新开始while,do-while,for语句，或者标签语句(label statement).

 - 当你使用没有带标签语句的连续语句(continue Statement)时，将在当前的while,do-while或者for循环体封闭的内部语句中止执行，然后进入下一次循环继续执行。与中断语句(break Statement)相比，连续语句不会把整个循环终止。在while循环里，将跳回条件判断(continue)；
 在for循环里，则调回累计表达式(increment-expression).
 - 当你使用带有标签语句的连续语句时，用于识别循环体中的标签语句。
 
 连续语句的语法如下：
 
 1.continue
 2.continue label

示例1
下面的例子实现了一个带有连续语句的while循环，当i的值为3时，该连续语句执行。因此，n的值分别为1、3、7和12。
```javascript
  i = 0;
  n = 0;
  while (i < 5) {
     i++;
     if (i == 3)
        continue;
     n += i;
  }  
```

示例2
一个标签语句checkiandj包含了一个标签语句checkj。如果连续语句被触发，程序会中止在当前循环中的checkj然后开始下一轮循环。每次连续语句被触发，checkj会重复直到该条件判断返回false值。当返回false值时，会完成剩下的checkiandj语句，然后checkiandj会重复直到其条件判断返回false值。当返回false值时，程序会继续执行在checkiandj后面的语句。

如果连续语句包含的是checkiandj标签，那么程序会在checkiandj语句的顶层继续执行。
```javascript
    checkiandj :
       while (i < 4) {
          document.write(i + "<br/>");
          i += 1;
          checkj :
             while (j > 4) {
                document.write(j + "<br/>");
                j -= 1;
                if ((j % 2) == 0)
                   continue checkj;
                document.write(j + " is odd.<br/>");
             }
          document.write("i = " + i + "<br/>");
          document.write("j = " + j + "<br/>");
       }
```

## 对象操作语句(Object Manipulation Statements)
JavaScript用for...in,for each...in和with语句来操作对象。

## 异常处理语句(Exception Handling Statements)
你可以用throw语句抛出一个异常并且用try...catch语句捕获处理它。

### 异常类型(Exception Types)
JavaScript可以抛出任意对象。然而，不是所有对象能产生相同的结果。尽管抛出数值或者字母串作为错误信息十分常见，但是通常用下列其中一种异常类型来创建目标更为高效：
 - ECMAScript exceptions
 - DOMException
 - nsIXPCException
 
### 抛出错误(throw Statement)
使用throw语句抛出一个异常。当你抛出异常，你规定一个含有值的表达式要被抛出。
```javascript
    throw expression
```

你可以抛出任意表达式而不是特定一种类型的表达式。下面的代码抛出了几个不同类型的表达式：
 - throw "Error"; //string type
 - throw 42;
 - throw true;
 - throw {toString:function(){return "I'm an object!"}};

```javascript
    //create an object type UserException
    function UserException (message){
        this.message = message;
        this.name = "UserException";
    }
    //Make the exception convert to a pretty string when used as a string (e.g. by the error console)
    UserException.prototype.toString = function(){
        return this.name + ': "' + this.message+ '"';
    }
    //create an instance of the object type and throw it
    throw new UserException("Value too high");
```

### try...catch语句
try...catch语句标记一块待尝试的语句，并规定一个以上的响应应该有一个异常抛出。如果我们抛出一个异常，try...catch语句就捕获它。

try...catch语句有一个包含一条或者多条语句的try代码块，0个或多个的catch代码块，catch代码块中的语句会在try代码块中抛出异常时执行。 换句话说，如果你在try代码块中的代码如果没有执行成功，那么你希望将执行流程转入catch代码块。如果try代码块中的语句（或者try 代码块中调用的方法）一旦抛出了异常，那么执行流程会立即进入catch 代码块。如果try代码块没有抛出异常，catch代码块就会被跳过。finally 代码块总会紧跟在try和catch代码块之后执行，但会在try和catch代码块之后的其他代码之前执行。

下面的例子使用了try...catch语句。示例调用了一个函数用于从一个数组中根据传递值来获取一个月份名称。如果该值与月份数值不相符，会抛出一个带有"InvalidMonthNo"值的异常，然后在捕捉块语句中设monthName变量为unknown。

```javascript
   function getMonthName(mo) {
     mo = mo - 1; // Adjust month number for array index (1 = Jan, 12 = Dec)
     var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
     if (months[mo]) {
       return months[mo];
     } else {
       throw "InvalidMonthNo"; //throw keyword is used here
     }
   }
   try { // statements to try
     monthName = getMonthName(myMonth); // function could throw exception
   }
   catch (e) {
     monthName = "unknown";
     logMyErrors(e); // pass exception object to error handler -> your own function
   }
```

### 捕捉块(The catch block)
你可以使用捕捉块来处理所有可能在try代码块中产生的异常。

```javascript
    catch(catchID){
        statements
    }

捕捉块指定了一个标识符 (上述语句中的catchID）来存放抛出语句指定的值；你可以用这个标识符来获取抛出的异常信息。在插入捕捉块时JavaScript创建这个标识符；标识符只存在于捕捉块的存续期间里；当捕捉块执行完成时，标识符不再可用。

举个例子，下面代码抛出了一个异常。当异常出现时跳到捕捉块（the catch block）。

```javascript
   try {
      throw "myException" // generates an exception
   }
   catch (e) {
   // statements to handle any exceptions
      logMyErrors(e) // pass exception object to error handler
   } 
```

### 终结块(The finally Block)
终结块包含了在try和catch块完成后、下面接着的try...catch语句之前执行的语句。终结块无论是否抛出异常都会执行。如果抛出了一个异常，就算没有异常处理，终结块里的语句也会执行。

你可以用终结块来令你的脚本在异常发生时优雅地退出；举个例子，你可能需要在绑定的脚本中释放资源。接下来的例子用文件处理语句打开了一个文件（服务端的JavaScript允许你进入文件）。如果在文件打开时一个异常抛出，终结块会在脚本错误之前关闭文件。

```javascript
   openMyFile();
   try {
       writeMyFile(theData); //This may throw a error
   }catch(e){
       handleError(e); // If we got a error we handle it
   }finally {
       closeMyFile(); // always close the resource
   } 
```

如果终结块返回一个值，该值会是整个try-catch-finally流程的返回值，不管在try和catch块中语句返回了什么：

```javascript
   function f() {
     try {
       console.log(0);
       throw "bogus";
     } catch(e) {
       console.log(1);
       return true; // this return statement is suspended
                    // until finally block has completed
       console.log(2); // not reachable
     } finally {
       console.log(3);
       return false; // overwrites the previous "return"
       console.log(4); // not reachable
     }
     // "return false" is executed now  
     console.log(5); // not reachable
   }
   f(); // console 0, 1, 3; returns false 
```

嵌套try...catch语句

你可以嵌套一个或多个try...catch语句。如果一个内部的try...catch语句没有捕捉块（catch block），将会启动匹配外部的try...catch语句的捕捉块（catch block）。

## 错误匹配对象(Utilizing Error objects)
根据错误类型，你也许可以用'name'和'message'获取更精炼的信息。'name'提供了常规的错误类(e.g., 'DOMException' or 'Error')，而'message'通常提供了一条从错误对象转换成字符串的简明信息。

在抛出你个人所为的异常时，为了充分利用那些属性（比如你的catch块不能分辨是你个人所为的异常还是系统的异常时），你可以使用错误构造函数（the Error constructor）。比如：

```javascript
   function doSomethingErrorProne () {
     if (ourCodeMakesAMistake()) {
       throw (new Error('The message'));
     } else {
       doSomethingToGetAJavascriptError();
     }
   }
   ....
   try {
     doSomethingErrorProne();
   }
   catch (e) {
     console.log(e.name); // logs 'Error'
     console.log(e.message); // logs 'The message' or a JavaScript error message)
   } 
```